#!/usr/bin/env bash
# Generate or export Sparkle EdDSA keys.
# Public key → Config/SparklePublicEDKey.xcconfig + project.yml
# Private key → secrets/sparkle_ed_private_key (gitignored)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS="$ROOT/secrets"
PUBLIC_XCCONFIG="$ROOT/Config/SparklePublicEDKey.xcconfig"
PRIVATE_KEY="$SECRETS/sparkle_ed_private_key"
DERIVED="${DERIVED_DATA:-$ROOT/.derivedData}"

mkdir -p "$SECRETS"

find_tool() {
  local name="$1"
  find "$DERIVED" "$ROOT/.derivedData-release" \
    -name "$name" -type f 2>/dev/null | head -1
}

GENERATE_KEYS="$(find_tool generate_keys || true)"

if [[ -z "$GENERATE_KEYS" ]]; then
  echo "==> Resolving Sparkle package to obtain generate_keys"
  command -v xcodegen >/dev/null && (cd "$ROOT" && xcodegen generate)
  xcodebuild -scheme ButterKeys -destination 'platform=macOS' \
    -derivedDataPath "$DERIVED" \
    CODE_SIGN_IDENTITY="-" CODE_SIGNING_ALLOWED=NO \
    build 2>&1 | tail -3 || true
  GENERATE_KEYS="$(find_tool generate_keys || true)"
fi

if [[ -z "$GENERATE_KEYS" ]]; then
  echo "Could not find Sparkle generate_keys after build." >&2
  exit 1
fi

echo "Using: $GENERATE_KEYS"

# Ensure a key exists in the login keychain (no-op if already present).
"$GENERATE_KEYS" >/tmp/sparkle-generate-keys.out 2>&1 || true
cat /tmp/sparkle-generate-keys.out

PUB="$("$GENERATE_KEYS" -p 2>/dev/null | tr -d '[:space:]')"
if [[ -z "$PUB" ]]; then
  PUB="$(sed -n 's/.*<string>\([^<]*\)<\/string>.*/\1/p' /tmp/sparkle-generate-keys.out | head -1)"
fi
if [[ -z "$PUB" ]]; then
  echo "Failed to read Sparkle public key" >&2
  exit 1
fi

if [[ ! -f "$PRIVATE_KEY" ]]; then
  echo "==> Exporting private key to $PRIVATE_KEY"
  "$GENERATE_KEYS" -x "$PRIVATE_KEY"
fi
chmod 600 "$PRIVATE_KEY"

cat > "$PUBLIC_XCCONFIG" <<EOF
// Generated by scripts/setup-sparkle-keys.sh — safe to commit (public key only).
SPARKLE_PUBLIC_ED_KEY = $PUB
EOF

python3 - "$ROOT/project.yml" "$PUB" <<'PY'
import pathlib, re, sys
path, pub = sys.argv[1], sys.argv[2]
text = pathlib.Path(path).read_text()
text, n = re.subn(
    r'(SPARKLE_PUBLIC_ED_KEY:\s*)"[^"]*"',
    rf'\1"{pub}"',
    text,
    count=1,
)
if n == 0:
    raise SystemExit("SPARKLE_PUBLIC_ED_KEY not found in project.yml")
pathlib.Path(path).write_text(text)
print("Updated project.yml SPARKLE_PUBLIC_ED_KEY")
PY

echo
echo "Public key: $PUB"
echo "Private key: $PRIVATE_KEY (gitignored — back this up)"
echo "Wrote $PUBLIC_XCCONFIG"
